# Generated by Django 5.0.7 on 2024-08-03 18:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_email_alter_account_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(
                max_length=600,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Text can't contain only spaces.", regex="^(?!\\s*$).+"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created_at"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created_at"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(
                max_length=1200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Text can't contain only spaces.", regex="^(?!\\s*$).+"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created_at"
            ),
        ),
    ]
